name: Sync to Hugging Face hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git config pull.rebase false
      
      - name: Fetch from hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git fetch https://reichaves:$HF_TOKEN@huggingface.co/spaces/reichaves/Chatbot-Gemma2-9b-It-all-MiniLM-L6-v2-Brazil-PDF main

      - name: Merge changes
        run: |
          git merge FETCH_HEAD --allow-unrelated-histories -m "Merge Hugging Face changes"
        continue-on-error: true

      - name: Check for merge conflicts
        run: |
          if git ls-files -u | grep -q '^'; then
            echo "Merge conflicts detected. Please resolve them manually."
            exit 1
          fi

      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://reichaves:$HF_TOKEN@huggingface.co/spaces/reichaves/Chatbot-Gemma2-9b-It-all-MiniLM-L6-v2-Brazil-PDF main
